<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Customers.Domain\Customers.Domain.csproj" />
    <ProjectReference Include="..\Customers.Contracts\Customers.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Platform\Platform.Core\Platform.Core.csproj" />
    <ProjectReference Include="..\..\..\Platform\Platform.Application\Platform.Application.csproj" />
  </ItemGroup>
</Project>
